version: "2"
services:
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:3'
    hostname: zookeeper
    ports:
      - '2181:2181'
    tmpfs: "/datalog"
    networks:
      - net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:2'    
    hostname: kafka 
    ports:
      - '9092:9092'
    expose:
     - "9093"
    networks:
      - net
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_CREATE_TOPICS: "prueba_topic"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:9093

#Se crea un network dentro de docker para que converse zookeeper y kafka en la misma red
networks:
  net:



# Para crear las imagenes y correrlas:
# docker-compose --project-name example up -d 